CREATE TABLE AGENT(
EMP_ID CHAR(6),
A_NAME VARCHAR (20),
EMAIL VARCHAR (20),
A_LOC_ADD VARCHAR(25),
PRIMARY KEY(EMP_ID)
);

CREATE TABLE A_REGION(
A_LOC_ADD VARCHAR(25),
A_REG VARCHAR(25)
);

CREATE TABLE CUSTOMER(
C_SSN CHAR(6),
C_NAME VARCHAR (20),
EMAIL VARCHAR (20),
C_LOC_ADD VARCHAR(25),
EMP_ID CHAR(6),
PRIMARY KEY(C_SSN),
FOREIGN KEY(EMP_ID) REFERENCES AGENT (EMP_ID)
);

CREATE TABLE C_REGION(
C_LOC_ADD VARCHAR(25),
C_REG VARCHAR(25)
);

CREATE TABLE NOMINEE(
N_SSN CHAR(6),
N_NAME VARCHAR (20),
EMAIL VARCHAR (20),
N_LOC_ADD VARCHAR(25),
C_SSN CHAR(6),
PRIMARY KEY(N_SSN),
FOREIGN KEY(C_SSN) REFERENCES CUSTOMER (C_SSN)
);

CREATE TABLE N_REGION(
N_LOC_ADD VARCHAR(25),
N_REG VARCHAR(25)
);


CREATE TABLE INSURANCE(
I_ID CHAR(6),
PREMIUM NUMERIC (8,2),
ISSUE_DT DATE,
EXPIRY_DT DATE,
C_SSN CHAR(6),
EMP_ID CHAR(6),
PRIMARY KEY(I_ID),
FOREIGN KEY(C_SSN) REFERENCES CUSTOMER (C_SSN),
FOREIGN KEY(EMP_ID) REFERENCES AGENT (EMP_ID)
);

CREATE TABLE HEALTH(
I_ID CHAR(6),
BMI NUMERIC(2,2),
GENETIC_DIS VARCHAR(25),
GEN_PHYS VARCHAR(25),
FOREIGN KEY (I_ID) REFERENCES INSURANCE(I_ID),
PRIMARY KEY(I_ID)
);

CREATE TABLE TRAVEL(
I_ID CHAR(6),
MODE_T VARCHAR(25),
REGION VARCHAR(25),
DURATION VARCHAR(20),
FOREIGN KEY (I_ID) REFERENCES INSURANCE(I_ID),
PRIMARY KEY(I_ID)
);